server.port: ${album-details-service.port}

opentracing:
  jaeger:
    http-sender:
      url: ${jaeger.endpoint}
    service-name: ${project.artifactId}
    enabled: true
    enable-b3-propagation: true
    log-spans: true