server.port: ${greeting-service.port}

service:
  cute-name:
    name: ${cute-name-service.endpoint}

spring:
  application:
    name: ${project.artifactId}
  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: ${jaeger.endpoint}

# Dekorate
dekorate:
  openshift:
    name: greeting-service
    expose: true
  s2i:
    builder-image: registry.access.redhat.com/ubi8/openjdk-11:1.14
