server.port: ${greeting-service.port}

service:
  cute-name:
    name: ${cute-name-service.endpoint}

opentracing:
  jaeger:
    http-sender:
      url: ${jaeger.endpoint}
    enable-b3-propagation: true
    log-spans: true
spring:
  application:
    name: ${project.artifactId}

# Dekorate
dekorate:
  openshift:
    expose: true
  s2i:
    builder-image: registry.access.redhat.com/ubi8/openjdk-8:1.3
