server.port: ${suggestion-service.port}

service:
  album:
    name: ${album-service.endpoint}
  store:
    name: ${store-service.endpoint}

opentracing:
  jaeger:
    http-sender:
      url: ${jaeger.endpoint}
    service-name: ${project.artifactId}
    enabled: true
    enable-b3-propagation: true
    log-spans: true